spring.application.name=postulacion
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbcaaa:hsqldb:mem:postulaciondb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

#SWAGGER CONFIG SOLO PERFIL DEV--
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.path = /api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha