# suppress inspection "UnusedProperty" for whole file
#CONFIGURACION GLOBAL
spring.profiles.active = dev
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.default_schema = public

spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
multipart.maxFileSize=100MB
multipart.maxRequestSize=100MB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
server.servlet.session.tracking-modes=cookie
spring.servlet.multipart.enabled = true
er-ui.tagsSorter=alpha

spring.datasource.url=jdbc:hsqldb:mem:usuariosdb;DB_CLOSE_DELAY=-1
spring.datasource.username=SA
spring.datasource.password=